### ISSUE TITLE
Add support for passing `browserConsole`, `startUrl` etc. to web-ext run

### ISSUE THREAD

**Issue by birtles** [hiikezoe/web-ext-webpack-plugin#1]
`web-ext run` supports a number of parameters such as showing the browser console on startup, specifying the start URL(s), specifying the Firefox version/profile etc..

It would be nice when using `web-ext-webpack-plugin` to be able to specify these so that one can configure it to always load a certain test page on startup etc.

**Comment by hiikezoe** [comment]
Thanks for reporting!

Now I pushed a few commits supporting browserConsole, startUrl, firefox and firefoxProfile options.   I did also try to add ignoreFiles option but it seems not work locally.  Anyway I think we need tests that doesn't use a mock of web-ext, does use the real web-ext, but I have no idea what the best way to do that.  I don't have enough knowledge in node.js world. :/

**Comment by birtles** [comment]
Amazing! Works perfectly. Thank you!
