### ISSUE TITLE
Clarify how to install this plugin in README

### ISSUE THREAD

**Issue by exoego** [hiikezoe/web-ext-webpack-plugin#13]
Hello.

I found this repository on [Mozilla's extension workshop](https://github.com/mozilla/extension-workshop/blob/fa5bb6b271c6ca3cf65972db06cb1fc3a22f7b6b/src/content/documentation/develop/browser-extension-development-tools.md)

It seems that this plugin is not published on npm.
Perhaps other place?

It would be helpful if how to install is clarified in README, something like:

```
npm install @XXXX/web-ext-webpack-plugin
```

**Comment by JimmyJim1** [comment]
Not  needed

**Comment by samuelroland** [comment]
@exoego I agree that it would be helpful. I found this repos at the same place than you.
I found a forked repos package on https://cnpmjs.org/package/@ianwalter/web-ext-webpack-plugin, but I don't know if it's safe... Any ideas ?

**Comment by samuelroland** [comment]
New info, the package from ianwalter contains "1 high severity vulnerability"... :
![image](https://user-images.githubusercontent.com/47849646/108134168-fb279980-70b5-11eb-8db5-01301cc40877.png)

**Comment by gl-pasci** [comment]
yeah...the "high severity" vulnerability is easy fixed with `npm audit fix`. Nothing to worry about. What baffles me the most is the amount of nonsense one have to pull to include a trivial file like this one. Sometimes is good to be a bit old school, so...just save it somewhere, import in webpack.config.js and happy coding!

**Comment by birtles** [comment]
I've updated the dependencies for this package and the README too. However, I can't yet publish it to npm with the name `web-ext-webpack-plugin` since it is too similar to existing packages. I've contacted npm support to see if they can help.

**Comment by birtles** [comment]
Note to self: Get https://extensionworkshop.com/documentation/develop/browser-extension-development-tools/ updated (via PR to https://github.com/mozilla/extension-workshop/blob/master/src/content/documentation/develop/browser-extension-development-tools.md) once this is published to npm.

**Comment by birtles** [comment]
This has now been published to npm as `web-ext-plugin` with the ctor etc. renamed to `WebExtPlugin` as well.
