### ISSUE TITLE
Plugin does not generate the extension zip file

### ISSUE THREAD

**Issue by bencergazda** [hiikezoe/web-ext-webpack-plugin#19]
I would assume a webpack production build generates also a zip file to `artifactsDir`, as to how `$ web-ext build` does.

**Comment by birtles** [comment]
Yeah, this is basically a wrapper for `web-ext run` and `web-ext lint` at the moment. I suppose we could add some way to trigger `web-ext build` too.

**Comment by bencergazda** [comment]
That would be great!

I submit a PR soon.

**Comment by birtles** [comment]
Fixed by #20 and released in version 1.3.0.
