### ISSUE TITLE
Stop watching when the browser running the extension is closed

### ISSUE THREAD

**Issue by nesbocaj** [hiikezoe/web-ext-webpack-plugin#28]
Currently `webpack -w` keeps running after closing the browser that is running the extension. This feels counter-intuitive to me, especially since that isn't the case for `web-ext run`.

It seems an easy fix would be changing https://github.com/hiikezoe/web-ext-webpack-plugin/blob/8091500a7f580f360366896d98a6486a5025208f/index.js#L117-L119 to:

```javascript
this.runner.registerCleanup(() => {
  if (compiler.watching && !compiler.watching.closed) {
    compiler.watching.close();
  }

  this.runner = null;
});
```

**Comment by birtles** [comment]
> > Perhaps it's some other plugin I can in my configuration that's interfering with it.
> 
> Could be, did you find out what was interfering with the webpack process termination?

I confirmed that `compiler.watching.close()` was being called and completing without error but unfortunately I didn't have time to debug it any further. Provided it works for you, that's enough for now. Maybe another day I'll have a chance to dig a bit deeper.

**Comment by nesbocaj** [comment]
Okay. Like I said, it works perfectly, so thanks for implementing this.
