### ISSUE TITLE
A config to disable lint.

### ISSUE THREAD

**Issue by AzrizHaziq** [hiikezoe/web-ext-webpack-plugin#35]
Hi really appreciate this webpack plugin. Reduce code cluttered on my side. 

As the title says, i would love to have another option to disable `lint`. Reason is, my extension output:
 - chrome manifest version 3 
 - add-ons manifest version 2
 
 For add-ons it works great, while for chrome `webExt.cmd.lint` throw this error and its stop running webpack watch.
 
 ```
 errors          1
notices         0
warnings        4

ERRORS:

Code           Message                              Description                           File   Line   Column
JSON_INVALID   "/manifest_version" should be <= 2   Your JSON file could not be parsed.
WARNINGS:
```

i belive this is coming from this [repo](https://github.com/mozilla/addons-linter), and i'm not sure how to disable this lint

thanks!

**Comment by birtles** [comment]
This seems like a reasonable request. I've added some code for this in 2fb2e108c2ba3159e1f1b1e9b9bce23096c0ce9f

**Comment by birtles** [comment]
I've released 1.8.0 with this fix. Please let me know if it works!

**Comment by AzrizHaziq** [comment]
work like a charm. Thank you very much sir

**Comment by birtles** [comment]
Thank you!
