### ISSUE TITLE
Incorrect TypeScript types

### ISSUE THREAD

**Issue by webdeveric** [hiikezoe/web-ext-webpack-plugin#38]
The options that are passed into `webExt.cmd.run()` should match the types that `web-ext` expects.

For example, you have `startUrl` as `string` where it should be `string[]`.

https://github.com/hiikezoe/web-ext-webpack-plugin/blob/165f8770a609ce31ae157b0bdc8e35a79e770e1f/index.d.ts#L18

https://github.com/mozilla/web-ext/blob/0becc28b0af4cadd743b0e5282b40386954565ec/src/cmd/run.js#L43

**Comment by birtles** [comment]
Interesting! Passing a string for the `startUrl` works (see https://github.com/mozilla/web-ext/blob/0becc28b0af4cadd743b0e5282b40386954565ec/src/extension-runners/firefox-desktop.js#L229-L234) so I guess the `web-ext` flow types are incomplete.

**Comment by webdeveric** [comment]
[`target` can be an array too.](https://github.com/mozilla/web-ext/blob/0becc28b0af4cadd743b0e5282b40386954565ec/src/cmd/run.js#L44)

**Comment by birtles** [comment]
> `target` can be an array too.

Thanks, should be fixed now.
