### ISSUE TITLE
web-ext-plugin does not fail Webpack build when web-ext execution fails

### ISSUE THREAD

**Issue by MikkCZ** [hiikezoe/web-ext-webpack-plugin#40]
**STR:**
1. Have an error in the extension, e.g. invalid manifest.
2. Run webpack with web-ext-plugin and linting enabled.

**Expected result:**
web-ext output contains an error and webpack execution fails.

**What actually happens:**
web-ext output contains an error, but webpack exists with exit code 0.

**Comment by birtles** [comment]
That seems to come down to this part:

https://github.com/hiikezoe/web-ext-webpack-plugin/blob/c3d7737e62c270e8eea52487f8fc0d4d65d50983/index.js#L59-L74

I guess if we set `warningsAsErrors: false` and `shouldExitProgram: true` we will start failing for critical errors in the manifest but continue working for warnings.

Hopefully that doesn't break anyone too badly and doesn't require a major version change.

**Comment by birtles** [comment]
Oh, wait, that doesn't work. `shouldExitProgram: true` will cause the whole thing to exit after running the lint step, even if it passes.

**Comment by birtles** [comment]
I've made lint errors abort the build but it might be nice if you could opt in to lint warnings also aborting so you can ensure new warnings are not introduced.
