### ISSUE TITLE
Add an option to disable or ignore specific linter errors when validating chrome extensions

### ISSUE THREAD

**Issue by MoralCode** [hiikezoe/web-ext-webpack-plugin#67]
This plugin provides a very convenient way to lint extensions when building. However,  due to https://github.com/mozilla/web-ext/issues/2532 it is inconvenient to use this for validating chrome extensions as the linting will essentially always fail

I think it would be nice to either:
- have a flag that allows specific lint results (i.e. MANIFEST_FIELD_UNSUPPORTED with a message matching `"/background" is in an unsupported format.`) to be ignored when deciding whether to fail or succeed at linting
- have a flag that treats all linter errors as warnings (similar to the existing flag, but the other way around)
- have a flag to indicate this is being used to validate a chrome extension that will change this linting step's idea of a "supported format" to match chrome's

Hope this is an acceptable/supported usecase (if not let me know). Happy to make this a contribution as well once I know which option (if any) would be preferred for the codebase.

**Comment by MoralCode** [comment]
yeah that makes sense! Do you think something like that would be relatively easy for a first-time contributor to the codebase to implement?

**Comment by birtles** [comment]
> yeah that makes sense! Do you think something like that would be relatively easy for a first-time contributor to the codebase to implement? Any hints on what documentation I could start with?

Sorry for the delay!

I'm afraid I didn't write this project, I just maintain it, but it's a very very simple project. There are no tests and there is no build step. All you need to do is clone the project and run `yarn install`.

Then you will want to modified `index.js`, add the option for disabling specific lint warnings, then filter them out somewhere before [here](https://github.com/hiikezoe/web-ext-webpack-plugin/blob/336af25dce6563ca5bbeb01ff8e1cf88ea14aae8/index.js#L107).

Finally, you will need to update `index.d.ts` to add the types for the new option.

Some day we should probably add some unit tests for this, e.g. using `vitest`. It's up to you if you want to do that now.
